# Roles for master and slave

- hosts: tag_name_master
  roles:
     - master-k8s-node

- hosts: tag_name_slave
  roles:
     - slave-k8s-node


# Create token in master and pass the taken into slave

- hosts: tag_name_master
  tasks:
  - name: run join cmd in master
    shell: "kubeadm token create --print-join-command"
    register: join_cmd_output

  - set_fact:
      shared_variable: "{{ join_cmd_output.stdout }}"

  - add_host:
      name: "joint_register"
      shared_variable: "{{ shared_variable }}"

- hosts: tag_name_slave
  vars:
    join_slave: "{{ hostvars['joint_register']['shared_variable'] }}"
  tasks:
  - name: Joining slave to master node
    shell: "{{ join_slave }}"


- hosts: tag_name_master
  tasks:
     - name: Apply flannel
       shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

     - name:
       copy:
          src: mysql.yml
          dest: /

     - name: Launch the mysql
       shell: kubectl apply -f /mysql.yml 

     - name: wordpress
       copy: 
         src: wordpress.yml
         dest: / 

     - name: Launch the wordpress
       shell: kubectl apply -f /wordpress.yml

     - name: expose the wordpress
       shell: kubectl expose pod wordpress --type=NodePort --port=80
       
     - name: service ip
       shell: kubectl get svc
       register: ip

     - name: host ip
       debug:
         var: ip

