apiVersion: v1
kind: Pod
metadata:
   name: "database"
   labels:
      db: mysql
spec:
   containers:
   - name: "database"
     image: "mysql:5.7"
     env:
     - name: MYSQL_ROOT_PASSWORD
       value: redhat
     - name: MYSQL_USER
       value: admin
     - name: MYSQL_PASSWORD
       value: redhat
     - name: MYSQL_DATABASE
       value: mydb
